nginx in openshift as reverse proxy
-----------------------------------

if you deployed an application in openshift-eap container which has an
internal address:

....
     localhost:8080/html5-frontend-1.0-SNAPSHOT/
....

and want to access it by openshift router hitting url path / it's not that simple.

You have several options to achieve it:

1.  Redeploy an app as ROOT.war

2.  Change router as it described https://docs.openshift.com/container-platform/3.11/install_config/router/customized_haproxy_router.html[here in OSE 3.11 documentation
]

3. Don’t expose router of JEE application but instead create an reverse
proxy with another container.

This example illustrate an deployment nginx as reverse proxy to other
eap applicaion inside same namespace in openshift:


*  Deploy you JEE application in openshift, but don’t expose route to
outside world. Your application is available to call in same namespace by
accessing a server name:

http://eap-app.nproject.svc:8080/html5-frontend-1.0-SNAPSHOT/


* Deploy nginx container with reverse proxy configuration:
+
....
 oc new-app  nginx~https://git.majorov.biz/nmajorov/nginx-openshift.git --name=nrp
....

Now nginx router will forward all requests to JEE application by hitting a / path.
